### ISSUE TITLE
Array size is not a small enough positive integer.

### ISSUE THREAD

**Issue by RonaldMiller17** [blaadje/fancyBar#2]
I installed Ubersicht and the widget, but this error shows when I try to load the widget. I am using chunkwm and installed the font awesome fonts. Am I missing something?

**Comment by johnallen3d** [comment]
It looks like the code has several references to `chunkbar.widget` in the path to scripts (renamed forked widget?). If you rename the folder from `fancyBar` to `chunkbar.widget` that should get you past this particular error.

**Comment by johnallen3d** [comment]
Well, I see now that the README says to clone into a folder named `chunkbar.widget`. I cloned the repo directly which resulted in a folder named `fancyBar`.

**Comment by RonaldMiller17** [comment]
> Well, I see now that the README says to clone into a folder named `chunkbar.widget`. I cloned the repo directly which resulted in a folder named `fancyBar`.

Yea I cloned into the chunkbar.widget folder so I don't think that's the issue.

**Comment by blaadje** [comment]
Hello @RonaldMiller17, could you try to remove the entire folder and try 
```bash
git clone https://github.com/blaadje/fancyBar.git $HOME/Library/Application\ Support/Übersicht/widgets/fancybar.widget
```

Let me know if you have any trouble but it should be fixed.

**Comment by brieucdlf** [comment]
Tried it and got: **undefined is not object (evaluating 'values[4].split')**
My folder is named: fancybar.widget

Nice bar btw :)

**Comment by RonaldMiller17** [comment]
@blaadje Tried that and I'm still having the same issue unfortunately. I'm wondering if this is an issue that only happens in Mojave, since I saw you were running this with High Sierra.

**Comment by giann** [comment]
Yes I have the same issue on Mojave, with that widget alone in Übersicht widget directory.

**Comment by blaadje** [comment]
Ok i'll take a look on Mojave and fix it asap 🙂

**Comment by matthewcm** [comment]
I am having this issue too with High Sierra.

**Comment by blaadje** [comment]
@TechDimension Well i have a few questions then :
- Do you have `chunkwm` installed and working ?
If you type `chunkc tiling::query -d id` in your terminal do you have the active workspace displayed ?

- What is your last commit `git log` ?

- Is the bar displayed and you have the error in your console, or is the error blocking the execution ?

I'll test it on different macosx version later but for me and a few people it seems to work without any issue

**Comment by RonaldMiller17** [comment]
Seems that my chunkwm was not properly set up. It's all working now! @blaadje

**Comment by giann** [comment]
I don’t have chunkwm. Should I ?

**Comment by blaadje** [comment]
@giann Yes, this bar was made to be used with chunkwm.

**Comment by ghost** [comment]
@RonaldMiller17 What did you do to fix the chunkwm issue? I am also getting undefined is not object (evaluating 'values[4].split')
